all: main pomiary

main: main.c 
	gcc main.c -o main

calka: calka.c 
	gcc calka.c -o calka

test: test.c 
	gcc test.c -o test

pomiary: pomiary.c
	gcc pomiary.c -o pomiary

clean: 
	rm main calka test pomiary
