
all: czysc reverse1 reverse2 rozmiar

czysc: czysc.c
	gcc czysc.c -o czysc

reverse1: reverse1.c
	gcc reverse1.c -o reverse1

reverse2: reverse2.c
	gcc reverse2.c -o reverse2

rozmiar: rozmiar.c
	gcc rozmiar.c -o rozmiar

cleanReverse:
	rm reverse reverse1 reverse2

clean:
	rm czysc rozmiar reverse reverse1 reverse2
